//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iBeacon_WcfServiceLibrary.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class BEACON_DEVICES
    {
        public int ID { get; set; }
        public string BEACON_ID { get; set; }
        public string BEACON_NAME { get; set; }
        public string BEACON_UUID { get; set; }
        public Nullable<int> BEACON_MAJOR { get; set; }
        public int BEACON_MINOR { get; set; }
        public Nullable<int> STORE_ID { get; set; }
        public Nullable<bool> IS_BROADCASTING { get; set; }
        public string SUBTITLE { get; set; }
        public int SELLING_GLASS { get; set; }
        public Nullable<bool> ACTIVE { get; set; }
        public string STATUS { get; set; }
    }
}
