//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iBeacon_WcfServiceLibrary.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITEMS_ADVERTISEMENT
    {
        public int ID { get; set; }
        public string GUID { get; set; }
        public string URL_IMAGE { get; set; }
        public Nullable<int> DEVICE_ID { get; set; }
        public Nullable<System.DateTime> START_DATE { get; set; }
        public Nullable<System.DateTime> END_DATE { get; set; }
        public Nullable<bool> IS_ACTIVE { get; set; }
        public Nullable<int> NUMBER_LIKE { get; set; }
        public Nullable<int> NUMBER_1_STAR { get; set; }
        public Nullable<int> NUMBER_2_STAR { get; set; }
        public Nullable<int> NUMBER_3_STAR { get; set; }
        public Nullable<int> NUMBER_4_STAR { get; set; }
        public Nullable<int> NUMBER_5_STAR { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<int> PRICE { get; set; }
    }
}
