//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iBeacon_WcfServiceLibrary.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class MALL
    {
        public int ID { get; set; }
        public string MALL_GUID { get; set; }
        public string MALL_NAME { get; set; }
        public string LOCATION_CODE { get; set; }
        public Nullable<int> BEACON_ID { get; set; }
        public Nullable<int> LAT { get; set; }
        public Nullable<int> LONG { get; set; }
        public string RADIUS { get; set; }
        public Nullable<bool> BROADCAST_ENABLE { get; set; }
    }
}
