//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iBeacon_WcfServiceLibrary.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class STORE
    {
        public int ID { get; set; }
        public string GUID { get; set; }
        public string STORE_NAME { get; set; }
        public Nullable<int> MALL_ID { get; set; }
        public Nullable<bool> BROADCAST_ENABLE { get; set; }
        public string HOME_PAGE { get; set; }
    }
}
